/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "EntityLink" CASCADE;

CREATE TABLE "EntityLink" (
  "account" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "id" INTEGER NOT NULL);

