/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Entity" CASCADE;

CREATE TABLE "Entity" (
  "id" INTEGER NOT NULL PRIMARY KEY,
  "world_id" INTEGER NOT NULL,
  "x" REAL NOT NULL,
  "y" REAL NOT NULL,
  "z" REAL NOT NULL,
  "x_grid" INTEGER NOT NULL,
  "y_grid" INTEGER NOT NULL,
  "body_id" INTEGER NOT NULL,
  "upcast_id" INTEGER NOT NULL);

