/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "PhysicsData" CASCADE;

CREATE TABLE "PhysicsData" (
  "id" INTEGER NOT NULL PRIMARY KEY,
  "shape_id" INTEGER NOT NULL,
  "height" REAL NOT NULL,
  "radius" REAL NOT NULL,
  "mass" REAL NOT NULL,
  "has_mass" BOOLEAN NOT NULL);

